name: dart_neoml
description: Dart NeoML is a port of the cross-platform library NeoML
version: 1.0.0+1
maintainer: Alexey Tropin (@shigomany)

homepage: https://github.com/shigomany/dart-neoml

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  ffi: ^1.2.1
  meta: ^1.8.0
  path: ^1.8.0
  platform_info: ^3.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


